# Generated by Django 5.0.6 on 2026-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautystore',
            name='logo_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_emoji',
        ),
        migrations.AddField(
            model_name='beautystore',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
